In [ ]:
# Please use the following code to visualize your predictions before submission
# You should have already validated the prediction format using validate_prediction_format.

In [1]:
import sys
sys.path.append('..')
from util.dataset_util import read_video, read_cam_params, project_3d_to_2d, plot_over_image, read_data, show_image, load_data_from_pickle, load_data_from_picklev2

In [2]:
data_test = '/Users/andreaongaro/Documents/Documenti Andrea Ongaro/Magistrale/Torino/Corsi/2_ANNO/ComputerVision/Project/lcn-pose/dataset/h36m_test.pkl'
data_pred_path = '/Users/andreaongaro/Documents/Documenti Andrea Ongaro/Magistrale/Torino/Corsi/2_ANNO/ComputerVision/Project/lcn-pose/dataset/h36m_test.pkl'  # prediction file to be submitted; replace this with your prediction
camera_name = '60457274' # select from ['50591643', '58860488', '60457274', '65906101']


# Test Version

In [11]:
import numpy as np
frame_id = 0
data = load_data_from_picklev2(data_test)
j3d = data[frame_id]["joint_3d_camera"]

T = data[frame_id]["camera_param"]["T"].reshape(1, 3)
R = data[frame_id]["camera_param"]["R"]

import json
with open("/Users/andreaongaro/Documents/Documenti Andrea Ongaro/Magistrale/Torino/Corsi/2_ANNO/ComputerVision/Project/lcn-pose/dataset/human3.6/camera-parameters.json", 'r') as f:
    data_camera = json.load(f)
instrinsics = {
    "f": [[data_camera["intrinsics"][camera_name]["calibration_matrix"][0][0],
           data_camera["intrinsics"][camera_name]["calibration_matrix"][0][1]]],
    "c": [[data_camera["intrinsics"][camera_name]["calibration_matrix"][0][2],
           data_camera["intrinsics"][camera_name]["calibration_matrix"][1][2]]],
    "k": [[data_camera["intrinsics"][camera_name]["distortion"][0],
           data_camera["intrinsics"][camera_name]["distortion"][1],
           data_camera["intrinsics"][camera_name]["distortion"][2],
           ]],
    "p": [[data_camera["intrinsics"][camera_name]["distortion"][3],
              data_camera["intrinsics"][camera_name]["distortion"][4],
              ]]

}
print("DATI 3D")
print(j3d)
j3d_in_camera = np.matmul(np.array(j3d) - T, np.transpose(R))
print("DATI 3D CONVERTITI")
print(j3d_in_camera)
j2d_camera = project_3d_to_2d(j3d_in_camera, instrinsics, 'w_distortion')
print("DATI 2D")
print(j2d_camera)
plot_over_image([], j2d_camera, path_to_write="/Users/andreaongaro/Documents/Documenti Andrea Ongaro/Magistrale/Torino/Corsi/2_ANNO/ComputerVision/Project/lcn-pose/visualization/images/test_h36m.png", show=True)

Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x1068a2430>>
Traceback (most recent call last):
  File "/Users/andreaongaro/.pyenv/versions/3.8.20/envs/py_cv/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 775, in _clean_thread_parent_frames
    def _clean_thread_parent_frames(
  File "/Users/andreaongaro/.pyenv/versions/3.8.20/envs/py_cv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 354, in __call__
    def __call__(self, frame, event, arg):
KeyboardInterrupt: 


DATI 3D
[[ -293.70004272  -525.02728271  5461.41845703]
 [ -178.39385986  -543.30645752  5503.42773438]
 [ -159.13841248   -75.73199463  5566.43310547]
 [ -104.66836548   389.71435547  5567.62792969]
 [ -409.00668335  -506.74810791  5419.40771484]
 [ -435.45193481   -38.3963623   5473.39453125]
 [ -444.93322754   429.27697754  5445.10546875]
 [ -281.53082275  -774.20568848  5402.734375  ]
 [ -274.37295532 -1016.6463623   5340.68701172]
 [ -285.05099487 -1134.47021484  5363.85009766]
 [ -259.22705078 -1221.703125    5293.50878906]
 [ -430.40402222  -983.10876465  5250.54541016]
 [ -695.34552002  -900.02642822  5147.06054688]
 [ -943.16308594  -885.0067749   5127.84326172]
 [ -103.8538208  -1005.06622314  5406.90917969]
 [  159.92860413  -957.22424316  5533.14648438]
 [  354.78973389  -959.05328369  5688.17578125]]
DATI 3D CONVERTITI
[[  -54.36295989 -5005.56513339  5105.23714741]
 [ -164.59237052 -5045.38397104  5064.51417329]
 [   20.2298374  -5020.92767331  4630.68359767]
 [  169.7783

TypeError: list indices must be integers or slices, not tuple

In [ ]:
j3ds = load_data_from_pickle(data_pred_path)
frame_id = int(action_name) - 139

# Predicted Version

In [ ]:
import numpy as np
frame_id = annotations[action_name]['fr_id']
j3d = j3ds[frame_id]
R = cam_params['extrinsics']['R']
T = cam_params['extrinsics']['T']
print(R.shape)
print(T.shape)
print(np.transpose(R).shape)
# Convert 3D joint coordinates to camera coordinates
# Note: The camera extrinsics are assumed to be in the format [R|T], where R is the rotation matrix and T is the translation vector.
# The translation vector T is subtracted from the 3D joint coordinates before applying the rotation.
# This is a common convention in computer vision, but you should verify that this is the case for your specific dataset.

print("DATI 3D")
print(j3d)
j3d_in_camera = np.matmul(np.array(j3d) - cam_params['extrinsics']['T'], np.transpose(cam_params['extrinsics']['R']))
print("DATI 3D CONVERTITI")
print(j3d_in_camera)
frame = frames[frame_id]
j2d_camera = project_3d_to_2d(j3d_in_camera, cam_params['intrinsics_w_distortion'], 'w_distortion')
print("DATI 2D")
print(j2d_camera)
plot_over_image(frame, j2d_camera)